# Profile: strong (IKEv2, AES256-GCM, SHA384, ECP384 only) - Left Peer
connections {
    strong-conn {
        version = 2
        local_addrs = 10.0.1.1
        remote_addrs = 10.0.1.2
        proposals = aes256gcm16-prfsha384-ecp384
        local {
            auth = psk
            id = left@tunneltwin.lab
        }
        remote {
            auth = psk
            id = right@tunneltwin.lab
        }
        children {
            strong-child {
                esp_proposals = aes256gcm16-ecp384
                local_ts = 10.0.1.1/32
                remote_ts = 10.0.1.2/32
                mode = tunnel
            }
        }
    }
}

secrets {
    ike-strong {
        id-1 = left@tunneltwin.lab
        id-2 = right@tunneltwin.lab
        secret = "TunnelTwinSecretStrong2026!"
    }
}
