# Profile: mixed (Prefers AES256/ECP384, accepts MODP_1024) - Left Peer
connections {
    mixed-conn {
        version = 2
        local_addrs = 10.0.1.1
        remote_addrs = 10.0.1.2
        proposals = aes256-sha384-ecp384, aes256-sha256-modp1024
        local {
            auth = psk
            id = left@tunneltwin.lab
        }
        remote {
            auth = psk
            id = right@tunneltwin.lab
        }
        children {
            mixed-child {
                esp_proposals = aes256-sha384-ecp384, aes256-sha256-modp1024
                local_ts = 10.0.1.1/32
                remote_ts = 10.0.1.2/32
                mode = tunnel
            }
        }
    }
}

secrets {
    ike-mixed {
        id-1 = left@tunneltwin.lab
        id-2 = right@tunneltwin.lab
        secret = "TunnelTwinSecretMixed2026!"
    }
}
