# Profile: legacy-cbc (IKEv2, AES128-CBC+SHA1, MODP_2048) - Right Peer
connections {
    legacy-cbc-conn {
        version = 2
        local_addrs = 10.0.1.2
        remote_addrs = 10.0.1.1
        proposals = aes128-sha1-modp2048
        local {
            auth = psk
            id = right@tunneltwin.lab
        }
        remote {
            auth = psk
            id = left@tunneltwin.lab
        }
        children {
            legacy-child {
                esp_proposals = aes128-sha1-modp2048
                local_ts = 10.0.1.2/32
                remote_ts = 10.0.1.1/32
                mode = tunnel
            }
        }
    }
}

secrets {
    ike-legacy {
        id-1 = right@tunneltwin.lab
        id-2 = left@tunneltwin.lab
        secret = "TunnelTwinSecretLegacy2026!"
    }
}
