# Profile: weak (IKEv1, 3DES-SHA1, MODP_1024) - Right Peer
connections {
    weak-conn {
        version = 1
        local_addrs = 10.0.1.2
        remote_addrs = 10.0.1.1
        proposals = 3des-sha1-modp1024
        local {
            auth = psk
            id = right@tunneltwin.lab
        }
        remote {
            auth = psk
            id = left@tunneltwin.lab
        }
        children {
            weak-child {
                esp_proposals = 3des-sha1-modp1024
                local_ts = 10.0.1.2/32
                remote_ts = 10.0.1.1/32
                mode = tunnel
            }
        }
    }
}

secrets {
    ike-weak {
        id-1 = right@tunneltwin.lab
        id-2 = left@tunneltwin.lab
        secret = "TunnelTwinSecretWeak2026!"
    }
}
